.travis.yml, README.md
To visualize the quality of the source code.
Introduce [Coveralls](https://coveralls.io).
Using [goveralls](https://github.com/mattn/goveralls).
* None
* None
=> Coverage measurement

cmd/git-chglog/initializer.go, cmd/git-chglog/main.go
git-chglog does not support Windows colors.
be nice
use go-colorable instead of native os.Stdout/os.Stderr. This doesn't break on Linux or macOS.
Tests on Windows are already broken.
=> support Windows colors

cmd/git-chglog/cli_test.go, cmd/git-chglog/config_test.go
Fixes some OS specific tests.
Be possible to test on Windows
Use of filepath.ToSlash()
Tests seems to be already broken.
=> some fixes of tests on Windows

.travis.yml, Gopkg.lock, Gopkg.toml, cmd/git-chglog/config_test.go, cmd/git-chglog/custom_template_builder.go, cmd/git-chglog/custom_template_builder_test.go, cmd/git-chglog/initializer.go, cmd/git-chglog/initializer_test.go, cmd/git-chglog/kac_template_builder.go, cmd/git-chglog/kac_template_builder_test.go, cmd/git-chglog/main.go, cmd/git-chglog/template_builder.go, cmd/git-chglog/variables.go, scripts/release.sh, vendor/gopkg.in/AlecAivazis/survey.v1/multiselect.go, vendor/gopkg.in/AlecAivazis/survey.v1/select.go, vendor/gopkg.in/AlecAivazis/survey.v1/validate.go
For `v0.2.0`.
The specification of the file path in the test case is supported for windows.
* None
* None
Related: #10 
Related: #9
=> New template and pass all the test cases with windows! and usability update.

cmd/git-chglog/main.go
Fix color output bug in windows help command.
* Use `mattn/go-colorable` io.Writer.
* None
* None
=> Fix color output bug in windows help command

chglog.go, chglog_test.go
I changed the error message when git-tag does not exist to a more comprehensible one.
* None
* None
* None
=> Change to kindly error message when git-tag does not exist

README.md, chglog.go, chglog_test.go, cmd/git-chglog/config.go, cmd/git-chglog/context.go, cmd/git-chglog/main.go, fields.go, testdata/type_scope_subject.md
Added `--next-tag` flag to treat commits that have not yet tagged as specified tag names.
This is a function to include the commit for creating CHANGELOG in the release commit.
**EXAMPLE:**
```bash
$ git-chglog --next-tag 1.0.0
```
* None
* None
* None
* None
=> Add `--next-tag` flag (EXPERIMENTAL)

cmd/git-chglog/config_builder.go, cmd/git-chglog/config_builder_test.go, cmd/git-chglog/custom_template_builder.go, cmd/git-chglog/custom_template_builder_test.go, cmd/git-chglog/kac_template_builder.go, cmd/git-chglog/kac_template_builder_test.go, cmd/git-chglog/questioner.go, cmd/git-chglog/template_builder.go, cmd/git-chglog/variables.go, cmd/git-chglog/variables_test.go
Add URL of output example for template style.
```
? What is your favorite template style?
❯ keep-a-changelog -- https://github.com/git-chglog/example-type-scope-subject/blob/master/CHANGELOG.kac.md
standard         -- https://github.com/git-chglog/example-type-scope-subject/blob/master/CHANGELOG.standard.md
cool             -- https://github.com/git-chglog/example-type-scope-subject/blob/master/CHANGELOG.cool.md
```
* None
* None
* None
* None
=> Add URL of output example for template style

chglog.go
don't access `commits[0]` when we can't find commits.
check commits lenght.
```
$ git commit -m foobar --allow-empty
$ git tag v1.0.0
$ git-chglog --next-tag 2.0.0 -o CHANGELOG.md
⌚️  Generating changelog ...
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/git-chglog/git-chglog.(*Generator).readVersions(0xc000086d00, 0xc00009b5c0, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/foobar/src/github.com/git-chglog/git-chglog/chglog.go:199 +0x827
github.com/git-chglog/git-chglog.(*Generator).Generate(0xc000086d00, 0x122e280, 0xc0000920a8, 0x0, 0x0, 0x0, 0x0)
```
=> fix: Panic occured when exec --next-tag with HEAD with tag

chglog.go
This PR adds the strings.Contains, strings.HasPrefix, strings.HasSuffix, strings.Replace, strings.Lower and strings.Upper to the set of functions
available for usage in the changelog template.
The added functions can be used to manipulate commit messages before rendering the changelog.
These new functions can be used, for example, to replace custom git commit markers (e.g. `[ci-skip]`) from the commit messages rendered to the changelog.
In addition, the `hasPrefix` and `hasSuffix` functions allow to easily filter out commits starting with a given prefix as described in https://github.com/git-chglog/git-chglog/issues/26 in situations where the commit messages are not always prefixed by a "chore" prefix. 
The functions provided by the `strings` package and added in this PR to the …
=> feat: add the contains, hasPrefix, hasSuffix, replace, lower and upper functions to Changelog template

chglog_test.go
I am using this package and was considering contributing to it.
I work on Windows and I noticed the tests don't all pass out of the box.
The tests `TestGeneratorWithTypeScopeSubject` and `TestGeneratorWithNextTag` fail on Windows.
The markdown generated uses `\r\n` because I'm on windows. Even though I have `\r\n` locally in my go workspace because i have `core.autocrlf=true` in my git configuration. I believe the backtick string removes the `\r` in order for consistency.
```
--- FAIL: TestGeneratorWithTypeScopeSubject (1.65s)
Error Trace:    chglog_test.go:257
Error:          Not equal:
expected: "<a name=\"unreleased\"></a>\n## [Unreleased]\n\n### Bug Fixes\n- **core:** Fix commit\n\n\n<a name=\"2.0.0-beta.0\"></a>\n## [2.0.0-beta.0] - 2018-01-03\n### Features\n- **context:** Online …
```
=> Fixing tests on Windows

.gitignore, README.md, chglog.go, chglog_test.go, cmd/git-chglog/config.go, cmd/git-chglog/context.go, cmd/git-chglog/main.go, cmd/git-chglog/main_test.go, tag_reader.go, tag_reader_test.go
Our project tags the git repo in many ways. Several CI pipeline will tag with different prefixes. But we only want to include certain tags in CHANGELOG.
This PR adds a flag `--tag-filter-pattern`. This flag specifies a regular expression and only matched tags will be included in change log.
Code change is tiny. No much special. The major change is in `tag_reader.go`.
NA
fixes #43
=> feat: Add --tag-filter-pattern flag.

README.md
This PR updates README.md to clean up some inconsistent blank lines, typos and formatting changes.
* Added hotlink for Homebrew to be consistent with Scoop entry
* Fix assorted typos
* Formatted git as `git` in a few places it had been missed
* Minor phrasing tweaks
* Remove extra blank lines to make sections consistent
Typos :-)
n/a, documentation edit only
{Please write here}
=> docs: Markdown cleanups in README.md

Gopkg.lock, chglog.go, tag_reader_test.go
Add `upperFirst` template function. This can be useful to print subjects (`{{ .Subject | upperFirst }}`) in changelog.
We'll get changelog like this whatever commits message started with capital letters or not.
FEATURES:
- Add support for additional volumes
- Add interpreter option to `wait_for_cluster_cmd`
=> feat: add upperFirst template function

README.md, chglog.go, cmd/git-chglog/config.go, cmd/git-chglog/context.go, cmd/git-chglog/main.go, cmd/git-chglog/main_test.go, cmd/git-chglog/variables.go, commit_extractor.go, commit_filter.go, commit_filter_test.go
I commited accidentally Improvement: Require kubernetes provider >=1.11.1 instead of improvement: Require kubernetes provider >=1.11.1 terraform-aws-modules/terraform-aws-eks@0c1ed0e. Then I found that there is no way to filter commits and map titles in a no case sensitive way.
It would be nice to add an option to enable or disable the case sensitive behavior on commits, commit_groups or notes.
This PR add `commits.filter_insensitive` option to filter commits in a case insensitive way.
Maybe we should add `commits.filter_sensitive`, `commits.filter_case_sensitive` option or a cli flag instead ? @wadackel any thoughts ?
fixes https://github.com/git-chglog/git-chglog/issues/63
=> feat: add option to filter commits in a case insensitive way

Makefile
=> chore: Fix Makefile typo

README.md, chglog.go, cmd/git-chglog/config.go, commit_extractor.go, commit_extractor_test.go
This PR adds a new `Custom` sorting type to CommitGroup. This gives the ability to organize and order the sections based on their priority rather than alphabetically. For example `Feature` has logical precedence over `Bug Fixes` in list of changes.
Now there's a dedicated configuration for it:
```yaml
options:
commit_groups:
sort_by: Custom <-- required keyword 
title_order:    <-- predefined ordered list of titles to apply sort with 
- feat
- fix
- enhance
- refactor
- perf
- docs
title_maps:
docs: Documentation
enhance: Enhancements
feat: Features
fix: Bug Fixes
perf: Performance Improvements
refactor: Code Refactoring
```
The reason for adding a `[]string{}` to hold the order is because in go all the map's keys get sorted for predictability so technically there's no way to depend on …
=> feat: Add 'Custom' sort_type to CommitGroup

README.md
This PR provides an update to the `README.md` to include instructions on [`asdf`](https://asdf-vm.com/) installation support with a [plugin](https://github.com/GoodwayGroup/asdf-git-chglog).
It adds an example set of instructions for how to use `asdf`.
Does the update to the `README.md` provide enough detail?
Here @GoodwayGroup we utilize `git-chglog` in all of our services to maintain a consistent changelog. This plugin provides a common way to manage the installation of the too regardless of OS and fits well within our ecosystem. We use `asdf` to manage tools for our SDLC on local machines.
N/A
=> chore(asdf): add asdf install support to README

.github/renovate.json
This add the initial configuration for the [Renovate Bot](https://www.whitesourcesoftware.com/free-developer-tools/renovate)
What it does for a go project: https://docs.renovatebot.com/golang/
Configuration options (there's a lot of them): https://docs.renovatebot.com/configuration-options/
Discussion around renovate started in this thread: https://github.com/git-chglog/git-chglog/pull/93#issuecomment-776891825
>
> NOTE: We will need to have a repo Admin [Install the App within Github for the Repo](https://docs.renovatebot.com/install-github-app/). I am happy to do this, but I am not an Admin for the repo. 
>
This will provide a consistent way to keep the project dependencies patched. Most importantly, as security patches are pushed to dependencies, we will get automatic notifications and …
=> chore(deps): add initial renovatebot configuration

cmd/git-chglog/questioner.go, go.mod, go.sum
Update `gopkg.in/alecaivazis/survey` to current mainline version `github.com/AlecAivazis/survey/v2`.
This is used within the `--init` command.
Updates the dependency location.
There is no change in interface from `v1` to `v2` with the features that we use within the module.
There are currently no specific tests that exercise the `questioner.go` code. As a result, I did compile and test locally. Everything looked solid.
fixes #105
=> fix(deps): update module gopkg.in/alecaivazis/survey.v1 to github.com/AlecAivazis/survey/v2

cmd/git-chglog/main.go, cmd/git-chglog/main_test.go, go.mod, go.sum
This PR updates the core CLI library we use ([urfave/cli](https://github.com/urfave/cli)) from v1 to v2.
> Migration guide https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md 
The [migration guide](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md) calls out the areas we would want to watch out for.
The biggest concern when migrating is the change that the library made to be more POSIX-compliant. They now enforce [Flags before args](https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args).
Luckily, the way `git-chglog` builds the `ActionFunc` means we do not have to worry about backwards compatibility moving forward with systems that use the tool within their CI. All actions are triggered via flags instead of delimited commands. …
=> fix(deps): update module github.com/urfave/cli to v2

cmd/git-chglog/logger.go, cmd/git-chglog/logger_test.go, go.mod, go.sum
This will update the emoji module to v2 while addressing this install error:
```
go: gopkg.in/kyokomi/emoji.v2@v2.2.8: parsing go.mod:
module declares its path as: github.com/kyokomi/emoji/v2
but was required as: gopkg.in/kyokomi/emoji.v2
```
Use the desired `github.com/kyokomi/emoji/v2` module declaration.
🍕 emoji 🥇 
Just trying to get these deps cleared to start looking at the more meaty stuff.
fixes #106
=> fix(deps): update module gopkg.in/kyokomi/emoji.v1 to github.com/kyokomi/emoji/v2

cmd/git-chglog/questioner.go
This is a hotfix for a bug identified in #111 and by @evanchaoli 
Shout out to @evanchaoli for calling out the fix in https://github.com/git-chglog/git-chglog/pull/52
The update to `survey` v2 uses a new type `survey.OptionAnswer` with the Answer response, was previously `string`.
The `questioner.go` file was the only place where I saw the `survey` module used. 
I missed this on the port to v2 in #108 Sorry for that.
fixes #111
refs #52
=> fix(init): support OptionAnswer form in survey/v2

cmd/git-chglog/main.go
This fixes the `BREAKING CHANGE` bug reported in #116
This correctly defines the aliases for the CLI flags as needed with the update to `urfave/cli` v2.
fixes #116
=> fix(short flags): correctly define cli flags with shorthands

cmd/git-chglog/main.go
`--template` and `--repository-url` flags were introduced in 0.11 but were not being used,
this fixes it.
=> fix: `--template` and `--repository-url` flags not being used

.github/workflows/release.yml, .github/workflows/test.yml, .goreleaser.yml, README.md, go.mod
I want to support `Darwin arm` builds
- bumps to golang `1.16`
- uses `goreleaser` version [>=0.157.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.157.0) , which the gh action does
If I missed maybe something :)
=> chore: bump golang to 1.16

README.md, chglog.go, chglog_test.go, cmd/git-chglog/config.go, go.mod, go.sum, tag_reader.go, tag_reader_test.go
Relates to #123.
While this does not introduce "per-branch" tag parsing it does allow an
alternative tag sorting method which maybe a better solution.
With this commit the user can decide to sort the tags by semver instead
of dates.
This is useful where repositories are utilizing a  stable branch model
and back-ports are interleaved with new releases.
For example, if your mainline is on v3.0.0 with it's last release
1/1/2021 and a back-port release of v2.0.1 is released on 1/2/2021,
sorting by semver will correctly order the change log producing
v2.0.0 -> v2.0.1 -> v3.0.0
This functionality is completely opt-in and defaults to the original
"date" sorting
Signed-off-by: ldelossa <louis.delos@gmail.com>
Explained in commit message.
Explained in commit message
Ensure that there are no …
=> feat: allow tag sorting by semver

chglog.go, chglog_test.go, commit_parser.go, commit_parser_test.go, fields.go, testdata/trimmed_body.md
When attempting to render a commit body below the summary line of the commit there are two problems:
1) The text needs to be indented two spaces to appear as part of the list.
2) Notes (e.g. BREAKING CHANGE) are included in the body and end up being repeating in a Notes section (if this is part of your template).
Users that want verbose changelogs will want the body of the commit to render as part of the unordered list element of the header.
To address 1 add an `indent` func to the template parsing.
To address 2 add a `TrimmedBody` to the `Commit` fields.
The `TrimmedBody` will include everything in `Body` but not any `Ref`s, `Note`s, or `Mention`s.
With both of these a template block like:
```
{{ if .TrimmedBody -}}
{{ indent .TrimmedBody 2 }}
{{ end -}}
```
Will render the trimmed down …
=> feat: add support for rendering .Body after .Subject as part of list

Makefile, cmd/git-chglog/main.go, cmd/git-chglog/version.go
This PR allows the build process to pass the `ldflags` parameter to the build to set the version based on tag. This is the first step for addressing #90. 
```
go build -ldflags=all="-X main.version=$(git describe --tags --always)" -o git-chglog ./cmd/git-chglog
```
- `make build` has been updated to generate the `main.version` value for a local build.
- [GoReleaser](https://goreleaser.com/environment/#using-the-mainversion) supports passing the `main.version` flag by default, so our release process is covered.
related #90
=> chore: use ldflags to pass version to build process

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, CHANGELOG.md, Makefile
This change makes for a more consistent output of the changlog such that we can achieve an automated tagging and release process for #90. The goal is to get the `make changelog` command to the point that we can run it with the expectations that:
1. The output will include the details that we want from the commits in the log.
1. The output will be idempotent.
This will also address the issues noted in #125. We are using `chore` more often in the repo and those are not currently captured. As such,  a `BREAKING CHANGE` note was missed in our current changelog. I added it in by hand in the previous release.
This PR adjust the structure of the `CHANGELOG.md` such that it will consider:
1. The `Type`, `Scope` and `Subject` in the header of a commit message.
1. `Types` of `feat`, `fix`, …
=> chore(CHANGELOG): regenerate CHANGELOG with type-scope and KAC template

README.md, cmd/git-chglog/config.go, cmd/git-chglog/context.go, cmd/git-chglog/main.go
First off, thank you for creating an awesome tool. We're using `git-chglog` in many open source repositories at New Relic and we would like to continue doing so.
~~The PR introduces **sorting tags by version number** instead of sorting by the date of tag creation. Users can still sort by date by passing the flag `--sort-by-date`. Using `--sort-by-date` will perform the original behavior of the `git-chglog` command.~~
Per request to integrate with the latest configuration updates from #124 (nice addition @ldelossa 🙂 ), this pull request introduces **sorting tags by semver version** using the `--sort [TYPE]` flag where `TYPE` is either `date` or `semver`.  Sort by date is still default behavior.
**Previous reasoning behind the idea:**
Since we support multiple major release branches of a …
=> feat: add `--sort [TYPE]` flag 

Makefile, README.md
This adds the `make release` target command. The command is dependent on the `changelog` target completing correctly.
It will:
1. Build the local copy of `git-chglog`
1. Update the `CHANGELOG`
1. Commit the changes
1. Tag the current HEAD
1. Push the `master` and `tag`
I broke down the steps to address #90 into these separate PRs over the last few days because I wanted to discuss each piece of work in isolation. This last piece is one where I think we need to be in alignment about what the automation should do.
This "does the job" of removing the the manual steps by wrapping them up in a single command.
How do we feel about the command pushing the tag and branch?
Do we want to have the push of the `tag` and `master` be a manual process?
Just to put this out there, I have used an …
=> chore: add make release target

.github/workflows/docker.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .goreleaser.yml, Dockerfile, README.md
It release a docker image for every release. I needed it in my Gitlab-ci to easily generate my changelog.
It builds and push an image to Dockerhub.
The dockerfile and the github actions files
You will need to create two secrets on the repo to authenticate to Dockerhub
fixes #132
=> feat: add docker image on release and master

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml, Makefile
Following up #135, adding two new targets to Makefile:
- `docker`: Build Docker image
- `push`: Push Docker image
Fixes #137
=> chore: add docker target to Makefile

README.md, chglog.go
User reported regression in template function behavior.
See #139 
It appears that `Sprig` flips the inputs of the `contains`, `hasPrefix`, `replace`
and `hasSuffix` `strings` methods. This appears to be the cause of the regression.
See: https://github.com/Masterminds/sprig/blob/master/functions.go#L149-L152
This results in a regression against the previous implementations of the template
functions.
List of Sprig template functions and comments to implementations: https://github.com/Masterminds/sprig/blob/master/functions.go#L149
I went back to the previous (pre-Sprig) implementation of our template functions to ensure that we cover any other functions that may have a change in interface. This is when I noted that `replace` has a change in behavior.
I have updated the `README` with a table …
=> fix(template): address regression in string functions for template engine

cmd/git-chglog/config.go
This was, accidentally, removed in part of one PR a while back and
caused the Custom sort to not work properly.
fixes #140
=> fix: add CommitGroupTitleOrder back to Options

processor.go, processor_test.go
This will add link for merge requests for gitlab style. See  https://github.com/git-chglog/git-chglog/issues/159 for more details.
It follow gitlab merge request links standards.
fixes https://github.com/git-chglog/git-chglog/issues/159
=> feat: Automatic link for gitlab merge requests

.github/workflows/ci.yml, .github/workflows/publish.yml, .github/workflows/release.yml
As of February 8th 2021, Github Actions (or GHA) now supports skipping commits! The following patterns are identified when attempting to skips a commit:
> [skip ci], [ci skip], [no ci], [skip actions], or [actions skip]
More information can be found in Github's February 8th [blog post](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)
This removes the unnecessary if-check manual step now that this feature is covered by Github Actions. 
Make sure the pipelines operate as they do today! Ensure they skip any commits with the pattern listed above!
N/A
N/A
=> ci(workflows): 🔧  Remove Manual if-contains-skip-check Github Workflows

README.md
Simply updates the Go install instructions to be compatible with go 1.17 and upwards.
=> docs: update Go install instructions
